name: CustomEnchantmentsPE
main: ZtechNetwork/CustomEnchants
version: 1.0.0-beta
api: [1.12.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
author: ZtechNetwork

softdepend: 
- WorldGuard
- WorldEdit
- Vault

commands:
  customenchantments:
   usage: /ce
   description: The main command for Custom Enchantments
